### PR TITLE
Adding Antora Documentation

### PR DESCRIPTION
**Pull request by volkflo**
I added a root module for navigation as we discussed it @msavy.

### CODE REVIEW

**Comment by msavy** [comment]
Would it be possible to just add the asciidoc files? We should use CI to build the actual output HTML/CSS to avoid conflating stuff together (and make it easier for contributors).

Other than that, LGTM.

**Comment by msavy** [comment]
BTW, I changed the default branch for this repo to the "antora" branch. Hope that's OK. If not, let me know!

**Comment by msavy** [comment]
I'll make a PR for the automated build via GitHub Actions in about 5 mins. We can deal with that separately 👍.

**Comment by volkflo** [comment]
Do you think we still need this PR? I think we are good now?

**Pull request closed without merging**
