### PR TITLE
add tabsblock to ui

### PR DESCRIPTION
**Pull request by svzieg**
**Whats this Pull-Request for**
This is the second part of the tabsblock feature (https://github.com/apiman/apiman-antora-ui/pull/2) to actually make the command available in the docs project.

### CODE REVIEW

**Review by msavy — APPROVED** [review]

**Comment by msavy** [comment]
Congratulations on your first contribution to Apiman @svzieg!

Sorry it took a long time for me to get around to reviewing and merging this.

**Comment by msavy** [comment]
This doesn't seem to work reliably for me. 

Should we be running a certain command to ensure it appears/is built?

**Comment by volkflo** [comment]
@msavy I think we have to refactor the docs for this to the new syntax:

```adoc
 * Usage:
 *
 *  [tabset]
 *  ====
 *  Tab A::
 *  +
 *  --
 *  Contents of tab A.
 *  --
 *  Tab B::
 *  +
 *  --
 *  Contents of tab B.
 *  --
 *  ====
```
The test you did seems to work for me as well:
image

**Comment by svzieg** [comment]
Yes @msavy , @volkflo  that's right. You have to use this syntax. At least that works in our documentation project.

At least it works for some of your docs:

https://www.apiman.io/apiman-docs/installation-guide/3.0.0-SNAPSHOT/registries-and-components/hazelcast.html#tabset1_properties-servlet

https://github.com/apiman/apiman-docs-installation-guide/blob/3ee6950673dfd463e5dc9142a5b05688232eafaa/modules/ROOT/pages/registries-and-components/hazelcast.adoc#L26

**Comment by msavy** [comment]
Yeah, thanks, I sorted it out but forgot to follow up. 

It was an issue with the name of the block, some upstream examples have it as `[tabs]` others as `[tabset]` and I hadn't noticed.

https://gitlab.com/antora/antora-asciidoctor-extensions/-/commit/083fff26530f690c7970a4e6bc804885f60ca0e4#6d1af1c1499a9a107ace62ab44d8153e1d28b1d2_0_8

**Pull request merged**
